---
title: "6414 Group Project - Telecom Customer Churn Modeling "
author: "Jared Babcock, Rishi Bubna, Marta Bras"
date: "`r Sys.Date()`"
output:  
    pdf_document:
      toc: true
      toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("LoadingData.R")
source("CSS.R")
```


# Explanatory Data Analysis

## Overview of the data

The database has data from 7,043 telecom customers, all located in California (USA). The average tenure of the customers is 32 months with an average churn rate of 59% and an average CLTV of 4,400$.

```{r}
summary_table <- dat %>% 
  summarize(`number observations(#)` = length(CustomerID),
            `average tenure (months)` = (mean(`Tenure Months`)),
            `min tenure (months)` = min(`Tenure Months`),
            `max tenure (months)` = max(`Tenure Months`),
            `average churn rate(%)` = mean(`Churn Score`),
            `min churn rate(%)` = min(`Churn Score`),
            `max churn rate(%)` = max(`Churn Score`),
            `average CLTV($)` = mean(CLTV),
            `min CLTV($)` = min(CLTV),
            `max CLTV($)` = max(CLTV))


summary_table <-  t(summary_table)

kable(summary_table, digits = 0, format = "latex", booktabs = T, caption = "Demo Table") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F)
```

```{r fig.align = "center"}
slices <- table(dat$`Churn Value`)
lbls <- c("churned", "not churned")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels
par(mfrow = c(1,2))
pie(slices,labels = lbls, col=j_colors)
mtext("Small Margins", side = 1, line = 1, cex = 0.8)

pie(slices,labels = lbls, col=j_colors,
   main="Churned vs not churned", cex.main=0.8)

```


## Distribution of the data

```{r, fig.height=5}
ggplot(dat, aes(x=`Churn Score`)) + 
  geom_histogram(binwidth = 5, fill = "grey") +
  ggtitle("Histogram of b_nuclei - Median imputation") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()) +
  theme(plot.title = element_text(size=11))  
```


```{r, fig.height=4}
ggplot_1 <- ggplot(dat, aes(y=`Churn Score`, x= Gender, color = Gender,  palette = "jco")) +
  geom_boxplot() +
  ggtitle("Boxplot of Gender") +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  axis.title.x =element_text(size=8),  axis.title.y = element_text(size=8)) +
  theme(plot.title = element_text(size=8)) 

ggplot_2 <- ggplot(dat, aes(y=`Churn Score`, x= `Senior Citizen`, color = `Senior Citizen`,  palette = "jco")) +
  geom_boxplot() +
  ggtitle("Boxplot of seniority") +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  axis.title.x =element_text(size=8),  axis.title.y = element_text(size=8)) +
  theme(plot.title = element_text(size=8)) 

ggplot_3 <- ggplot(dat, aes(y=`Churn Score`, x= Dependents, color = Dependents ,  palette = "jco")) +
  geom_boxplot() +
  ggtitle("Boxplot of dependents") +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  axis.title.x =element_text(size=8),  axis.title.y = element_text(size=8)) +
  theme(plot.title = element_text(size=8)) 

ggplot_4 <- ggplot(dat, aes(y=`Churn Score`, x=`Phone Service`, color =`Phone Service`,  palette = "jco")) +
  geom_boxplot() +
  ggtitle("Boxplot of phone service") +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),  axis.title.x =element_text(size=8),  axis.title.y = element_text(size=8)) +
  theme(plot.title = element_text(size=8)) 

ggarrange(ggplot_1,ggplot_2, ggplot_3, ggplot_4, nrow = 2, ncol =2)
```
