---
title: "Clustering analysis"
author: "Marta Bras"
date: "11/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
set.seed(1680) # for reproducibility

library(dplyr) # for data cleaning
library(ISLR) # for college dataset
library(cluster) # for gower similarity and pam
library(Rtsne) # for t-SNE plot
library(ggplot2) # for visualization # clustering algorithms & visualization
source("DataTransformation.R")
```

```{r}
#removing NA
dat.reduced_C <- na.omit(dat.reduced_C)
dat.reduced_D <- dat.reduced_C[c(10,11,12,13,15,17, 30, 34)]
dat.reduced_D$`Churn Value` = as.factor(dat.reduced_D$`Churn Value`)
dat.reduced_D$Reason = as.factor(dat.reduced_D$Reason)

gower_dist <- daisy(dat.reduced_D[, -7],
                    metric = "gower",
                    )
summary(gower_dist)
gower_mat <- as.matrix(gower_dist)
dat.reduced_D[
  which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]),
        arr.ind = TRUE)[1, ], ]


# Output most dissimilar pair

dat.reduced_D[
  which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]),
        arr.ind = TRUE)[1, ], ]
```
```{r}
# Calculate silhouette width for many k using PAM

sil_width <- c(NA)

for(i in 2:10){
  
  pam_fit <- pam(gower_dist,
                 diss = TRUE,
                 k = i)
  
  sil_width[i] <- pam_fit$silinfo$avg.width
  
}

# Plot sihouette width (higher is better)

plot(1:10, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width")
lines(1:10, sil_width)

```

```{r}
pam_fit <- pam(gower_dist, diss = TRUE, k = 3)

pam_results <- dat.reduced_D %>%
  dplyr::select(-`Churn Value`) %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))

pam_results$the_summary
```

```{r}
tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)

tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering),
         default = dat.reduced_D$`Churn Value`)

ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster))
```

