---
title: "Decision_tree"
author: "Rishi Bubna"
date: "03/12/2019"
output: html_document
---

```{r setup}
  library(knitr)
  opts_knit$set(root.dir=normalizePath('../'))
  opts_chunk$set(fig.path = "../figures/", dev='pdf') # corrected path and added dev
```

```{r, include=FALSE}
source("./Logistic Regression/DataTransformation.R")
```

# Creating training and testing datasets

```{r}

set.seed(1)
names(dat.reduced_2)<-str_replace_all(names(dat.reduced_2), c(" " = "." ))

split = sample.split(dat.reduced_2$`Churn.Value`, SplitRatio = 0.75)
train = subset(dat.reduced_2, split == TRUE)
test = subset(dat.reduced_2, split == FALSE)
```


```{r}
library(tree)
library(tidyverse)

```

```{r}
decision_tree <- tree(Churn.Value~., data = train)
```

```{r}
plot(decision_tree)
text(decision_tree)
```

```{r}
decision_tree_cv <- cv.tree(decision_tree)
plot(decision_tree_cv$size,decision_tree_cv$dev, type ='b')
```

```{r}
decision_tree_pruned <- prune.tree(decision_tree, best = 5)
plot(decision_tree_pruned)
text(decision_tree_pruned)
```

```{r}
thresholds = array() 
accuracies = array() 

for (threshold in seq(0,1,by=0.1)){
  
thresholds = c(thresholds,threshold)
  
predicted_churn_score <- predict(decision_tree_pruned)
predicted_churn_score <- predicted_churn_score[,2]

predicted_churn_score[predicted_churn_score < threshold] = 0
predicted_churn_score[predicted_churn_score >= threshold] = 1
  

count=0
for (i in 1:length(predicted_churn_score)) {
if(predicted_churn_score[i] == train$Churn.Value[i]) count = count+1
}
accuracy=count/length(predicted_churn_score)
accuracies = c(accuracies,accuracy)

}

plot(thresholds,accuracies, type ='b')
print(accuracies)
```

```{r}
predictTrain = predict(decision_tree_pruned)[,2]
table(train$`Churn.Value`, predictTrain > 0.5)
```

Sensitivity: 509/(893+509)=0.36
Specificity: 3643/(3643+229) = 94%

```{r}
library(ROCR)
ROCRpred = prediction(predictTrain, train$`Churn.Value`)
ROCRperf = performance(ROCRpred, "tpr", "fpr")
# Plot ROC curve
plot(ROCRperf, colorize=TRUE, print.cutoffs.at=seq(0,1,by=0.1), text.adj=c(-0.2,1.7))
```

